FROM node:20-alpine3.21

WORKDIR /app

RUN apk add --no-cache \
    git \
    curl \
    python3 \
    make \
    g++ \
    sqlite \
    sqlite-dev \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV CHROMIUM_PATH=/usr/bin/chromium-browser
ENV PORT=55771
ENV HOST=0.0.0.0

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm@9 && pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 55771

CMD ["npm", "run", "start"]
